title: dhananjaya 
email: dhananjayaswain99@gmail.com
description: >- 
 A journal for tracking my present activities.s
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thelastone07.github.io" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  thelastone07

# Build settings

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap



markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge


collections:
  journals:
    output: true
    permalink: /journal/:title/

  blogs :
    output: true
    permalink: /blog/:title/


defaults:
  - scope:
      path: ""
      type: "blogs"
    values:
      math: true

    